# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa50dbe52a5880cdfd66ac1d1cb741b533dee89df127e1e35c2cfba6b448a224f1171bd4b80e892c4f6a751fb0e6433ddc9a425729c543573b03e6cba98266fe

test:
  secret_key_base: d21c8e5d58cc02a2f734f0dec19b775a9ce7deacb1a7ffbf5c4aa53a97e42759ab2fe3c3654173a198c7079e6ede64770e90edcb0f1a6041e6353059a3e6ed43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
